# Site
repository: sproogen/resume-theme
#favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 이현준
title: Data Engineer / Database Engineer
email: lalsakiel@gmail.com
# email_title: Email (Email title override)
# phone_title: Phone (Phone title override)
website: https://dev.to/hj_lee
website_title: Blog

# Dark Mode (true/false/never)
darkmode: true

# Social links
#github_username: Sibeet
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
linkedin_username: 현준-이-b338bb223
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  실시간 데이터를 파이프라이닝하고 데이터 인프라를 관리하는 데이터 엔지니어입니다.<br>
  Database 솔루션 회사에서 기술지원직으로 일한 경력을 바탕으로 데이터 거버넌스에 대한 방향성을 수립하고 사용자들에게 원하는 데이터를 제공해주고 있습니다.

  초기 경력에서는 DB 엔지니어로서, DB 초기 구성부터 성능 개선, SQL tuning, DBMS 관리 등 DBA role의 업무를 수행했습니다 <br>
  대규모 금융권 사이트, 통신사 사이트에서 업무를 지원하였고, 공공, 통신권 차세대 프로젝트를 런칭했습니다. <br>

  데이터 엔지니어로서 오케스트로에서 기존의 단순한 데이터 수집 및 사용 방식을 효율적으로 개선하기 위해 <br>
  Data Lake, Data Mart, Data Catalog 등의 간소화된 새로운 데이터 시스템 모델을 제안하고 구축했습니다. <br>
  최근에는 Airflow 도입을 제안하여 체계적이고 자동화된 데이터 파이프라인을 사내에 제공하고 있습니다.<br>

  사용자들이 쉽게 접근할 수 있는 데이터를 제공하기 위해 오픈소스 기반의 각종 데이터 도구들(prometheus, opensearch, datahub, influxdb, grafana...)에 관해 리서치하고 아키텍처를 구상했습니다.
  클라우드 기반의 사업 기반에 따라 k8s, openstack 등의 각종 가상화, container 시스템을 기반으로 데이터 인프라를 관리하고 점검, 개선하고 있습니다. 
  
  주요 기술: <mark>RDBMS</mark> <mark>SQL</mark> <mark>k8s</mark> <mark>airflow</mark> <mark>prometheus</mark>

content:
  - title: Experience 
    layout: list 
    content:
      - layout: left
        title: 선재소프트
        sub_title: 책임연구원 
        caption: 2017.10 ~ 2022.06
        quote: >
          국산 In-memory RDBMS 데이터베이스 솔루션 개발 회사로, Sharding, Clustering, online Scale-out 등을 강점으로 강력한 기술력을 보유한 회사입니다.
        description: | 
            - DBMS 기술지원, 시스템 컨설팅
            - DBMS 전반적인 설치, 지원과 동시에 프로젝트 전반적인 DBA, DB 관련 Project Leading
            - Query Tuning, 시스템 성능 튜닝 등의 시스템 개선
            - 성능 테스트, 기능 비교 등 경쟁사와의 비교 리서치
      - layout: left
        title: 오케스트로
        sub_title: 책임연구원 / 파트장
        caption: 2023.05 ~ 현재
        quote: >
          Cloud CMP / Okestration 솔루션 개발 회사로, 주요 클라우드 사업 분야에서 유니콘 스타트업으로 손꼽히는 회사입니다.
        description: |
            - ELK 아키텍쳐 Data pipeline 유지보수, 개선사항 관리
            - k8s 기반 Data pipeline 아키텍쳐 구성
            - 사내 데이터 관련 인프라 구성 / 개선
            - 파편화된 데이터 취합, 공통화 진행
            - 데이터 카탈로그 등을 통한 인사이트 제시

  - title: Skill
    layout: list 
    content:
      - layout: left
        title: Database
        caption: 데이터베이스 관리, DBA role, 쿼리 튜닝
        description: |
          - Query tuning, Query processing, SQL
          - Replication, Backup, Clustering, CDC
          - MVCC architecture
          - Mysql, mariadb, Postgresql, goldilocks

      - layout: left
        title: Infrastructure
        caption: 인프라 구성, 운영, 모니터링
        description: |
          - Linux, Linux shell, Linux monitoring
          - container, k8s, docker
          - minio, s3
      
      - layout: left
        title: Data engineering
        caption: 데이터 인프라, 데이터 엔지니어링
        description: | 
          - opensearch(elasticsearch), kafka, logstash, beat
          - prometheus
          - Airflow
          - Datahub 
          - harbor

  - title: Projects 
    layout: list 
    content:
      - layout: left
        title: LGU+ Ucube 차세대
        caption: 2021.08 ~ 2022.04
        description: |
          - LGU+ 통신 차세대 프로젝트로 과금시스템 원장 시스템 DB 구축
          - 4 by 2의 대용량 클러스터링 구성으로 총 TPS 15000 가량의 대규모 시스템
          - 가상 코어를 사용하는 솔루션 최초의 프로젝트로서, 가상 코어로 인한 성능 이슈 트래킹
          - 과금 시 발생하는 대량의 트랜잭션을 관리하고 개선 방안을 제안
          - Table별 적합한 Sharding key 모델링, 데이터 분산 처리
          - 대량 TPS로 인해 발생하는 heap 메모리 문제 등 전체적인 시스템 모니터링
          - 운영 초기 패치 이슈로 인한 on-line rolling 패치 진행

      - layout: left
        title: 케이뱅크 FDS시스템
        caption: 2018.06 ~ 2021.07
        description: | 
          - 금융권 이상탐지를 위한 FDS 시스템 DB 구축
          - 1 by 2 의 Replication 구조로 이루어져 있으며 솔루션 초기 Cluster 이슈를 담당
          - OLTP성 대용량 데이터(200~300GB)의 데이터 복제 한계로 인해, 개선방안을 제안하고 장기적인 운영방안 수립
          - online scale-up 요구사항에 맞춰 케이스를 테스트하고 아키텍쳐를 분석
          - 초기 구축시 예상하지 못했던 slow query를 분석, 튜닝

      - layout: left
        title: 법무부 바이오 고속검색시스템
        caption: 2021.09 ~ 2021.02
        description: |
          - 생체인식정보(지문, 얼굴) 데이터를 통한 대용량 검색 시스템 DB 구축
          - row당 2k단위 대용량 byte 데이터 처리
          - 2 by 2의 대용량 클러스터링 구성으로 데이터 분산, 병렬 처리 아키텍쳐를 제안
          - sharding을 통한 2T 이상의 대용량 데이터 분산 처리
          - OLAP성 시스템에 따른 읽기 병목 등 시스템 개선
          - full scan 기준 40분 가량 걸리던 시스템을 쿼리, 시스템(클러스터링 재구성) 튜닝으로 5분으로 단축 

  - title: Enhancement
    layout: list 
    content:
      - layout: top-middle
        title: 메트릭 데이터 플랫폼 품질 개선
        description: |
          <br>
          - 데이터 주기적 관리를 위한 opensearch ISM 정책 제안, 운영 환경 적용
          - opensearch clustering 구성, 운영 방안, 백업 정책 확립
          - 대용량 log 데이터 관리를 위한 external storage 적용 제안, 운영 적용(opensearch-s3, minio)
          - 메트릭 수집 다변화 리서치, Prometheus-thanos-s3 아키텍쳐 적용, 테스트
          - 팀 내부 인원 prometheus 교육
        
      - layout: top-middle
        title: 플랫폼 데이터 통합 프로젝트
        description: |
          <br>
          - 솔루션 플랫폼별로 분산되어 있는 데이터를 통합하기 위한 프로젝트를 제안, 진행
          - 흩어져있는 수집 데이터를 한 곳으로 통합하고 데이터 저장소를 규격화(opensearch, prometheus, mariadb)
          - 가공이 필요한 2차 데이터는 Airflow를 제안, 아키텍쳐를 설계하고 데이터 파이프라인 작성
          - Datahub를 사용하여 데이터 카탈로그를 만들고 내부 인원들이 파이프라인, 데이터 description 등을 쉽게 조회할 수 있는 플랫폼 생성
          - 오프라인 기반의 인프라 구성으로 인한 오픈소스 아키텍쳐 파악, 내부 운영에 맞는 k8s 배포 방법 작성

  - title: Education 
    layout: list 
    content:
      - layout: top-middle
        title: 금오공과대학교
        caption: 2007 - 2017
        sub_title: 컴퓨터소프트웨어공학과

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
